### ISSUE TITLE
Enhance site design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#10]
* [x] Add logo on top left and link it to http://fossasia.org
* [x] Create a dropdown menu "Events" with all FOSSASIA events and include FOSSASIA 14/FOSSASIA 15, which are currently on the top bar (similar to FOSSASIA.org site), that expands on scroll over
* [x] About.html
   * [x] Add the information of about.html on the bottom of the index.html
   * [x] Forward about.html to index.html
   * [x] Link "about" to anchor "#about" on index.html page
   * [x] Create an automatic forward from "about.html to "index.html#about"
* [x] On right side bar delete "subscribe widget" from all pages
* [x] On http://2012.fossasia.org/exhibition.html there are links to pictures in the first paragraph. Include these pictures on the page itself instead of setting links.
* [x] On top bar menu add links "Blog" to blog.fossasia.org and "Contact" to http://blog.fossasia.org/contact/

**Comment by ankitrgadiya** [comment]
I'm working on it, you can assign this to me.

@mariobehling

**Comment by ankitrgadiya** [comment]
I cannot fix the dropdown, required Javascript sorry. Other than that all are fixed now. :-)

**Comment by mariobehling** [comment]
@ankitrgadiya Yes, JS is fine.

If the user goes to http://2012.fossasia.org/schedule.html and clicks on "About", the user is directed to http://2012.fossasia.org/schedule.html#about

It only works from the the index page. Please help to fix it.

**Comment by ankitrgadiya** [comment]
>If the user goes to http://2012.fossasia.org/schedule.html and clicks on "About", the user is directed to http://2012.fossasia.org/schedule.html#about

@mariobehling I'm on it

>I cannot fix the dropdown, required Javascript sorry. Other than that all are fixed now. :-)

By this I wanted to say that I don't know JS. 😄
