### ISSUE TITLE
Text Align

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/2012.fossasia.org#104]
Right now the site is a bit haywire and aligning the text will somewhat fix it
also i am working on it

**Comment by harshit98** [comment]
@samyakbvs what's the status of this issue?

**Comment by supunTE** [comment]
Can I work on this

**Comment by ParthS007** [comment]
@samyakbvs Please close this if resolved 👍

**Comment by ParthS007** [comment]
closing it due to insufficient information 👍
