### ISSUE TITLE
Improve mobile site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#11]
Please help to get the mobile site closer to the fossasia.org site:

* [ ] Include a top bar with a fossasia home logo and top right menu icon
![screenshot from 2016-12-14 04-33-12](https://cloud.githubusercontent.com/assets/1583873/21160195/7f15376a-c1b6-11e6-99a1-03fa414dd69e.png)
* [ ] Adopt colors and mobile menu items
* [ ] Ensure there are no internal scroll bars

![screenshot from 2016-12-14 04-31-15](https://cloud.githubusercontent.com/assets/1583873/21160222/9c1e1b4c-c1b6-11e6-9dfc-cf3f3ce7b5a2.png)

**Comment by duttaditya18** [comment]
On it!

**Comment by nzec** [comment]
I am working on it!
