### ISSUE TITLE
Remove header on other page

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/2012.fossasia.org#118]
When clicked on the menu I was navigated to the page just fine but the header persist & it looks like you're staying on the same page.

**Schedule page**

![image](https://user-images.githubusercontent.com/32614202/34398382-16ff88b2-ebb1-11e7-9cc4-69edf7cc2b85.png)

**Workshop page**

![image](https://user-images.githubusercontent.com/32614202/34398387-278d2662-ebb1-11e7-8536-82c37338339f.png)

**Comment by harshit98** [comment]
@Ploypiti what's the status of this issue? Are you working on it?

**Comment by Ploypiti** [comment]
@harshit98 I'm working on it.
