### ISSUE TITLE
Improper Layout in mobile formats

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/2012.fossasia.org#128]
### Problems : 

- **buttons in the top cover are not correctly positioned in phones resolutions**

- **buttons appear a lot lower in phone layouts.**

# Screenshots : 

![image](https://user-images.githubusercontent.com/5800726/34466830-0af33cae-ef07-11e7-9901-d373e9e1a3ca.png)
![image](https://user-images.githubusercontent.com/5800726/34466832-19b1139c-ef07-11e7-9fc5-d0be76027539.png)

**Comment by ParthS007** [comment]
@0x48piraj  Please update your status and close if resolved 👍

**Comment by 0x48piraj** [comment]
Someone copied my Pull Request :blush:

**Comment by 0x48piraj** [comment]
Closing it :+1:
