### ISSUE TITLE
No github link in the footer

### ISSUE THREAD

**Issue by newbazz** [fossasia/2012.fossasia.org#135]
![image](https://user-images.githubusercontent.com/25884863/34517178-f7f2ffdc-f09f-11e7-8ca8-d0c95026296b.png)
No github link in the footer.
Yes i would like to work on this issue.

**Comment by newbazz** [comment]
can someone tell me which file to look for this issue.

**Comment by abishekvashok** [comment]
@newbazz  https://github.com/fossasia/2012.fossasia.org/blob/gh-pages/_includes/footer.html
