### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/2012.fossasia.org#136]
- Contents are poorly aligned on desktop & iPad, everything is aligned to the left, leaves unnecessary blank space on the right.

![image](https://user-images.githubusercontent.com/32614202/34518775-972cf766-f0b3-11e7-92c9-68e83365ca35.png)

![ipadss](https://user-images.githubusercontent.com/32614202/34518619-b1126284-f0b2-11e7-806a-661d1480a5aa.jpg)

- Lacks padding on phone

![iphonexss](https://user-images.githubusercontent.com/32614202/34518812-c169c9a0-f0b3-11e7-8c89-ac3eccadfb0d.jpg)

------------

Working on it (as GCI task).

**Comment by ParthS007** [comment]
@Ploypiti Please update your status or close if resolved 👍
