### ISSUE TITLE
Error thrown while running server

### ISSUE THREAD

**Issue by newbazz** [fossasia/2012.fossasia.org#149]
Error thrown while running server 
![image](https://user-images.githubusercontent.com/25884863/34651739-f53d9736-f3f9-11e7-8330-1fceccca7ff2.png)

**Comment by abishekvashok** [comment]
@newbazz would you like to work on it?

**Comment by newbazz** [comment]
Yeah i would

**Comment by YashKumarVerma** [comment]
Good work @newbazz 
Next time,we could have commit message with #<issue> , that'd be great.
Then your issue could be reached easily. 
Cheers 😄
