### ISSUE TITLE
Convert md files into native html files

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/2012.fossasia.org#151]
Convert md files into native html files so that we can have better styling and content like the other summit sites. It will also allow us to do in depth styling.

Need review as to whether this can be done @fossasia/fossasia-gci

**Comment by abishekvashok** [comment]
Also it would be awesome if you could check whether this is an advanced issue, and if any of the points I asked is yes, I would like to work on it :)

**Comment by samyakbvs** [comment]
@abishekvashok maybe we should collaborate on this?

**Comment by abishekvashok** [comment]
@samyakbvs sure. But it would be best to do when a mentor finds this appropriate.
Ping @fossasia/fossasia-gci
