### ISSUE TITLE
Add scroll effect to internal site links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#16]
On many FOSSASIA sites we have a scroll effect for internal site links.

Please add it here as well, e.g. to http://2012.fossasia.org/index.html#about

**Comment by alejoheredia** [comment]
@mariobehling Do you mean, something like the navbar of PSLab website?

**Comment by mariobehling** [comment]
Yes, please.

**Comment by alejoheredia** [comment]
Ok, I will work on this issue

**Comment by 0x48piraj** [comment]
I want to work on this issue :+1:

**Comment by nzec** [comment]
I beleive #41 fixes this issue.

**Comment by 0x48piraj** [comment]
@duttaditya18 
I think you're so engrossed to do the task that you forgot the Rules !
Don't you think, you should have asked me before starting the work ? :-1: 
I'm working on this, since yesterday!
Now, what should I do ?

**Comment by nzec** [comment]
@0x48piraj I am very sorry. But I thought that you might have abandoned this task because this takes about 10 - 20 minutes and you assigned this task to yourslef 10 hours ago.

I am very sorry and will keep this in mind moving forward.

**Comment by 0x48piraj** [comment]
I prefer a clean work than doing this, _(I was having a discussion in gitter channel.)_
![image](https://user-images.githubusercontent.com/5800726/33606306-0ea395f8-d9e3-11e7-81f8-0c3ad10a7a25.png)

> And, the task length is 7 days. Everybody is not like you :blush:

**Comment by nzec** [comment]
I am very sorry. I am a beginner and I am making mistakes. I told you I will not repeat this again.
I am surprised that someone as experienced as you are getting angry over this small issue.

**Comment by akshatnitd** [comment]
@duttaditya18 Make sure you claim an issue before working on it and ask your co-developers before working on it, if they already have claimed it. Learn to respect your co-developers and work together, which doesn't lead to anyone's effort going in vain.

@0x48piraj No issues. You can work on other issues.

**Comment by 0x48piraj** [comment]
@fossasia/website-admins 
We should refrain students by doing this! :+1: 
It puts a bad impression for beginners.
A similar incident happened yesterday, and one **GCI** student was really pissed off.

> I am not getting angry my friend @duttaditya18, I will do any other task, not a problem. I am just saying this because of the yesterday's event. A GCI Student left FOSSASIA. I don't want this to happen again :blush: 

#### I'm happy for you! Keep doing blazing fast work like this :stuck_out_tongue:

**Comment by akshatnitd** [comment]
@0x48piraj True :)

**Comment by nzec** [comment]
Thanks for the help @akshatnitd 
@0x48piraj As I said earlier, I won't repeat this again. 😃
