### ISSUE TITLE
Add correct links to featured designers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#164]
Featured designers have wrong links. Please correct them.

**Comment by adityac8** [comment]
Hey @mariobehling  I was working on this and was unable to find some designers' certain social media pages. Should I just remove these buttons from their profile?

**Comment by adityac8** [comment]
@anshumanv @mariobehling I think we can close this one 😸

**Comment by anshumanv** [comment]
There are still some wrong links, please help correct them too. :smile:

**Comment by supunTE** [comment]
![image](https://user-images.githubusercontent.com/33794760/47543013-dc59d380-d8fd-11e8-963e-3719ea693f66.png)
Is these links are correctly linked? if not can I work? @anshumanv @mariobehling

**Comment by anshumanv** [comment]
Please investigate if there are any broken/wrong links and report them here, then send a PR.
