### ISSUE TITLE
Update and correct schedule as outlined on linked PDFs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#165]
The schedule data at https://2012.fossasia.org/#schedule is not entirely correct. 

1) Please correct the left column using the data in https://github.com/fossasia/2012.fossasia.org/blob/gh-pages/ODW-Program-Preparation-OpenDesignWeek-1.pdf
2) Please correct the middle column using the data in https://github.com/fossasia/2012.fossasia.org/blob/gh-pages/ODW-Program-Preparation-OpenDesignWeek-2.pdf

**Comment by Jeewal** [comment]
https://github.com/fossasia/2012.fossasia.org/pull/175/commits
