### ISSUE TITLE
Fix tweets 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#166]
The tweet section has some issues. Please help to fix it.

![screenshot from 2018-03-31 15-21-40](https://user-images.githubusercontent.com/1583873/38160901-4c1e0066-34f7-11e8-8d5e-d959a0a56119.png)

**Comment by adityac8** [comment]
Hey @mariobehling If [this app](https://foss2012.herokuapp.com/) looks fine, should I generate a PR?

**Comment by prekshajagetiya123** [comment]
Can I work on this issue?

**Comment by kksinghal** [comment]
@mariobehling Can we add a twitter widget in place of this ?

**Comment by saarthakchats** [comment]
I am fixing this @mariobehling
