### ISSUE TITLE
Left Align all headings and add sub items in menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#17]
As an example check: http://2012.fossasia.org/schedule.html
"Open Design Week 1" should be left aligned and it should be in a dropdown menu on the schedule with a direct link.
Please implement:
* [ ] Schedule
   * [ ] Dropdown menu: Open Design Week 1
   * [ ] Dropdown menu: Open Design Week 1
* [x] http://2012.fossasia.org/designers.html - left align all headings
* [x] http://2012.fossasia.org/workshops.html - left align headings
   * [ ] Dropdown menu: INTRODUCTORY WORKSHOPS
   * [ ] Dropdown menu: COMPANY WORKSHOPS
   * [ ] Dropdown menu: FONT DESIGN
*  [ ] http://2012.fossasia.org/design.html - left align
   * [ ] Dropdown menu: OPEN DESIGN CAMP SAIGON
   * [ ] Dropdown menu: MAKER CAMP CANTHO

**Comment by oanarosca** [comment]
I'll work on this! :)

**Comment by mariobehling** [comment]
Issue is not solved.

**Comment by 0x48piraj** [comment]
We should close this thread :blush:
