### ISSUE TITLE
Fix sidebar toggle btn

### ISSUE THREAD

**Issue by kksinghal** [fossasia/2012.fossasia.org#189]
When the user first opens the side bar , his mouse cursor moves  very far away from  the elements he was earlier on and then have to move the mouse a long distance to reach that sidebar toggle button again . 
[Sidebar BUG.mp4.zip](https://github.com/fossasia/2012.fossasia.org/files/2593100/Sidebar.BUG.mp4.zip)

**Comment by arihantbansal** [comment]
The mouse pointer isn't moving. On clicking the hamburger menu, the entire page shifts.
