### ISSUE TITLE
Schedule Timelines are not properly aligned

### ISSUE THREAD

**Issue by hritikgupta** [fossasia/2012.fossasia.org#205]
The timelines are not center-aligned in Medium Sized screens.

![schedule](https://user-images.githubusercontent.com/24262284/49690384-33d29c80-fb56-11e8-8def-29e9088d4ba6.png)

**Comment by saumyasrivastava08** [comment]
Can I work on this issue?

**Comment by hritikgupta** [comment]
Hey @saumyasrivastava08, sure go ahead!

**Comment by hritikgupta** [comment]
Hey @saumyasrivastava08 , #206 solves this issue; closing it.
