### ISSUE TITLE
Separate html and css

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#24]
CSS is included in the html. Please separate the css from html and link all pages to use the same CSS.

**Comment by abishekvashok** [comment]
I want to work on this too!

**Comment by yashNadun** [comment]
@Abhi2424shek can I work on this or are you doing this?

**Comment by idealadarsh** [comment]
@Abhi2424shek Are you working on this, please tell me which issue you are working on currently 24 or 25?
