### ISSUE TITLE
Move logo to left and implement same distance between menu items

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#25]
* [x] Move logo to left as shown in screenshot
* [x] On top bar implement even distance between all menu items

![screenshot from 2016-12-26 11-18-27](https://cloud.githubusercontent.com/assets/1583873/21480516/f8e2464a-cb5d-11e6-8a67-3b5428a39be3.png)

**Comment by abishekvashok** [comment]
I would like to work on this, this can be easily achieved with CSS

**Comment by Elgayar** [comment]
Can I use bootstrap? However, the design will change, to the better of course. It will be much more user friendly and responsive. @mariobehling

**Comment by mariobehling** [comment]
Changing the whole site to bootstrap for these small issues would be too much of a change. Please help to fix the small existing issues without implementing another framework. That should be sufficient. Thank you.

**Comment by mariobehling** [comment]
@Abhi2424shek @Elgayar Any updates on the issue?

**Comment by Elgayar** [comment]
I finished putting the logo on the left, however making equal spacing is the thing I'm stuck on.
I can't seem to know the reason causing unequal spacing, but I'm still working on it.

**Comment by Elgayar** [comment]
Bingo! Solved it, pull request in a minute.

**Comment by Elgayar** [comment]
![image](https://cloud.githubusercontent.com/assets/6567844/21592814/83c4194e-d119-11e6-999e-22ceb81150e2.png)
@mariobehling

**Comment by niccokunzmann** [comment]
Nice.

**Comment by Elgayar** [comment]
@niccokunzmann I'll issue a new pull request, because I messed up in the previous one.

**Comment by niccokunzmann** [comment]
It looked good to me.

**Comment by Elgayar** [comment]
Issue solved! You can close :)

**Comment by mariobehling** [comment]
@Elgayar Thank you. Please also ensure there is the same distance on the right hand side of the menu bar as on the left hand side to keep the style.
![screenshot from 2017-01-02 18-14-13](https://cloud.githubusercontent.com/assets/1583873/21593430/4aefef46-d117-11e6-96f5-b85ef2479541.png)

**Comment by mariobehling** [comment]
There should be some space on the right of the FOSSASIA dropdown menu.

**Comment by Elgayar** [comment]
Yeah, I'll do that right now,

**Comment by mariobehling** [comment]
Great.

I also see that in the dropdown menu of "FOSSASIA" the items in the menu do not display fully e.g. "FOSSASIA Summit 2015". Maybe reduce the size of the font in the dropdown menu.

There is also a follow up issue here about other dropdown menu items: https://github.com/fossasia/2012.fossasia.org/issues/17

**Comment by Elgayar** [comment]
Yeah, I can solve that as well!
I'll get it done soon.

**Comment by 0x48piraj** [comment]
This should be closed as well :+1:
