### ISSUE TITLE
Error on FOSSASIA 12 site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#3]
http://2012.fossasia.org/
The website encountered an unexpected error. Please try again later.
Error message
PDOException: SQLSTATE[28000] [1045] Access denied for user 'web2012'@'localhost' (using password: YES) in lock_may_be_available() (line 167 of /usr/www/users/opentek/2012fossasia/includes/lock.inc)

**Comment by tradzik** [comment]
Page needs reinstallation. In progress (as in email).
