### ISSUE TITLE
Add FOSSASIA footer to all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#30]
The footer is currently rudimentary and the design broken.

Please implement the FOSSASIA footer on the site.

![screenshot from 2017-01-02 15-04-59](https://cloud.githubusercontent.com/assets/1583873/21590528/004a6904-d0fd-11e6-998d-02e1ab636030.png)

**Comment by abishekvashok** [comment]
@mariobehling working on it...

**Comment by mariobehling** [comment]
Footer is not as expected.

![screenshot from 2017-12-06 19-46-43](https://user-images.githubusercontent.com/1583873/33679154-3611e9ba-dabe-11e7-83cb-310b73040468.png)

**Comment by mariobehling** [comment]
![screenshot from 2017-12-06 19-50-17](https://user-images.githubusercontent.com/1583873/33679319-bc614704-dabe-11e7-9c2c-f2d6920f1890.png)

**Comment by nzec** [comment]
Working on it as well as #38. @mariobehling
