### ISSUE TITLE
Add same top menu design as on FOSSASIA main site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#38]
FOSSASIA.org has a nice top menu bar. Please add a top menu that has the same design.

**Comment by 0x48piraj** [comment]
Claiming! :heart: 

BTW, @mariobehling 
*Just wanted to know, What should we do of the dissimilarities ?*

![image](https://user-images.githubusercontent.com/5800726/33336961-88ab5288-d497-11e7-960d-39c0a10198fd.png)
![image](https://user-images.githubusercontent.com/5800726/33336981-94f06fb0-d497-11e7-98a9-a0aa9956266e.png)

**Comment by 0x48piraj** [comment]
Any comments ? @mariobehling :wink:

**Comment by duttaditya18** [comment]
Working on it!

**Comment by 0x48piraj** [comment]
Don't you dare @duttaditya18 👎

**Comment by 0x48piraj** [comment]
Just wait for a week, and I will assign it to you, if I fail to send a PR. Don't waste efforts. Collaborate! 👍
