### ISSUE TITLE
Make gray background same as on fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#55]
The gray background is different to fossasia.org. Please implement the same.

**Comment by saarthakchats** [comment]
Where? The background is white. Where do you want me to change it?

**Comment by abishekvashok** [comment]
Colors are different @saarthakchats

**Comment by saarthakchats** [comment]
Arre but where?

**Comment by nzec** [comment]
Is it supposed to be `#f5f5f5` or `#333333`?

**Comment by harshit98** [comment]
@duttaditya18 Can you fix it? Please go ahead.

**Comment by abishekvashok** [comment]
@duttaditya18 @saarthakchats can I do it if you aren't in it, pls?
