### ISSUE TITLE
Avoid using external fonts and take out fontawesome.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#56]
For this simple website we want to keep the dependencies low. Therefore please take out external fonts and ensure fonts are working directly from the site.

**Comment by YashKumarVerma** [comment]
working on it

**Comment by nzec** [comment]
Font Awesome is only 30kb. I don't think it will be creating any problems. And if I take out Font Awesome, how will the icons be added?

**Comment by YashKumarVerma** [comment]
A local copy of the same will be added to the repository. I have done the changes and will be pushing the same today

**Comment by YashKumarVerma** [comment]
@mariobehling sir,
how about removing the other dependencies too? like jquery and bootstrap too ?

**Comment by mariobehling** [comment]
@YashKumarVerma Internal dependencies are ok. Bootstratp and jquery seem to be ok.

**Comment by YashKumarVerma** [comment]
so issue solved ?
@mariobehling

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/34009910-bdc276fe-e130-11e7-9ea6-65e890231e3d.png)
Icons working with local deployment
