### ISSUE TITLE
Center content area and ensure padding is equal on left and right

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2012.fossasia.org#57]
In a recent PR the content area was changed and is not centered anymore in the way that the padding on the left and right is equal.

* Please implement in a way that distance to edge is equal on both sides.

![screenshot from 2017-12-08 10-42-19](https://user-images.githubusercontent.com/1583873/33760041-b510c7da-dc04-11e7-85a5-8d34ed65e6b6.png)

* Please ensure a larger padding between main area and right sidebar

![screenshot from 2017-12-08 11-03-54](https://user-images.githubusercontent.com/1583873/33760882-9955261e-dc07-11e7-88f3-3e37e77018fe.png)

**Comment by abishekvashok** [comment]
@mariobehling working on it.
