### ISSUE TITLE
Website styling and documentation improvements

### ISSUE THREAD

**Issue by kubami9** [fossasia/2012.fossasia.org#60]
# How it looks now?
Currently all content is in a 860px white wrapper and background is grey. 
Sidebar displays on mobile devices very weird creating big space with no content at the bottom. 
README file contains only project name and its website.
It's a small thing in many FOSSASIA website social icon in the footer section are changing its color to grey or white once you hover on them

# How to fix/improve it?

- [x] delete wrapper and change background color to white
- [x] fix side-bar bug so it doesn't create empty space at the bottom
- [x] improve documentation by saying few words about the website, adding explanation about files and more general info
- [x] add hover effect on social media icons in the footer section

# Would you like to work on it?
Sure!

_This whole section and documentation needs more improvements so of course feel free to create new issues or add something to this one_ 😃

**Comment by anshumanv** [comment]
GFI @kubami9 :smile:
