### ISSUE TITLE
Github icon

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/2012.fossasia.org#80]
There is a "?" instead of a GitHub icon in the footer

**Comment by NaviRocker** [comment]
That is to, If you find any Problems or Errors with the Site, You can click it.

**Comment by arjunpandey2003** [comment]
@samyakbvs if you are not working can i

**Comment by RajKhare** [comment]
Can I work?

**Comment by harshit98** [comment]
@RajKhare Please go ahead. You can take up this issue.

**Comment by arjunpandey2003** [comment]
@harshit98 i think the current svg was added because, If you find any Problems or Errors with the Site, You can click it. According to @naveentherocker .

**Comment by ParthS007** [comment]
@samyakbvs Please close this if resolved 👍
